/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries

SELECT 
    COUNTRY, 
    COUNT(CUSTOMER_KEY) TOTALCUSTOMERS
FROM GOLD.dim_customers
GROUP BY COUNTRY
ORDER BY TOTALCUSTOMERS DESC

-- Find total customers by gender

SELECT 
    GENDER, 
    COUNT(CUSTOMER_KEY) TOTALCUSTOMERS
FROM GOLD.dim_customers
GROUP BY GENDER
ORDER BY TOTALCUSTOMERS DESC

-- Find total products by category

SELECT 
    CATEGORY, 
    COUNT(PRODUCT_KEY) TOTALPRODUCTS
FROM GOLD.dim_products
GROUP BY CATEGORY
ORDER BY TOTALPRODUCTS DESC


-- What is the average costs in each category?

SELECT 
    CATEGORY, 
    AVG(COST) AVGCOST
FROM GOLD.dim_products
GROUP BY CATEGORY
ORDER BY AVGCOST DESC


-- What is the total revenue generated for each category?

SELECT 
    P.CATEGORY, 
    SUM(F.SALES_AMOUNT) TOTALREVENUE
FROM GOLD.fact_sales F
LEFT JOIN GOLD.dim_products P
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY CATEGORY
ORDER BY TOTALREVENUE DESC

-- What is the total revenue generated by each customer?

SELECT
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.lAST_NAME,
    SUM(F.SALES_AMOUNT) TOTALREVENUE
FROM GOLD.fact_sales F
LEFT JOIN GOLD.dim_customers C
    ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
GROUP BY 
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.lAST_NAME
ORDER BY TOTALREVENUE DESC


-- What is the distribution of sold items across countries?

SELECT 
C.COUNTRY,
SUM(F.quantity) SOLDITEMS
FROM GOLD.fact_sales F
LEFT JOIN GOLD.dim_customers C
ON C.customer_key = F.customer_key
GROUP BY COUNTRY
ORDER BY SOLDITEMS DESC
